"use client";

import { useEffect, useMemo, useState } from "react";
import { BarChart3, Coins, TrendingUp } from "lucide-react";
import { supabase, type OrderRow } from "@/lib/supabase";
import { formatPrice } from "@/lib/utils";

export default function AdminMetricsPage() {
  const [orders, setOrders] = useState<OrderRow[]>([]);
  useEffect(() => { supabase.from("orders").select("*").then(({ data }) => setOrders(data || [])); }, []);
  const metrics = useMemo(() => { const sizes: Record<string, number> = {}; const models: Record<string, number> = {}; orders.forEach((order) => (order.items || []).forEach((item: any) => { if (item.size) sizes[item.size] = (sizes[item.size] || 0) + Number(item.quantity || 1); const name = item.name || item.title; if (name) models[name] = (models[name] || 0) + Number(item.quantity || 1); })); const paid = orders.filter((order) => order.deposit_paid).reduce((sum, order) => sum + (order.is_preorder ? Number(order.total_amount) * 0.5 : Number(order.total_amount)), 0); const pending = orders.filter((order) => !order.balance_paid && order.is_preorder).reduce((sum, order) => sum + Number(order.total_amount) * 0.5, 0); return { sizes: Object.entries(sizes).sort((a, b) => b[1] - a[1]).slice(0, 6), models: Object.entries(models).sort((a, b) => b[1] - a[1]).slice(0, 6), paid, pending, revenue: orders.reduce((sum, order) => sum + Number(order.total_amount), 0) }; }, [orders]);
  return <div className="section-padding mx-auto max-w-7xl"><div className="mb-8"><p className="label-caps">Lectura del juego</p><h1 className="heading-section mt-2">Métricas</h1><p className="mt-3 text-sm text-ivory/60">Indicadores calculados sobre los pedidos registrados.</p></div><div className="grid gap-4 sm:grid-cols-3"><Kpi icon={BarChart3} label="Pedidos" value={String(orders.length)} detail="Total histórico" /><Kpi icon={Coins} label="Recaudado" value={formatPrice(metrics.paid)} detail="Señas y ventas cobradas" /><Kpi icon={TrendingUp} label="Saldo pendiente" value={formatPrice(metrics.pending)} detail="Encargos por cobrar" /></div><div className="mt-6 grid gap-6 lg:grid-cols-2"><Chart title="Talles más demandados" data={metrics.sizes} suffix=" pedidos" /><Chart title="Botines más encargados" data={metrics.models} suffix=" unidades" /><div className="border border-white/10 bg-charcoal-50/60 p-5 lg:col-span-2"><h2 className="font-display text-xl text-ivory">Desglose financiero</h2><div className="mt-6 space-y-4"><Finance label="Recaudado" value={metrics.paid} total={metrics.revenue} color="bg-gold" /><Finance label="Saldos pendientes" value={metrics.pending} total={metrics.revenue} color="bg-amber-300" /></div></div></div></div>;
}
function Kpi({ icon: Icon, label, value, detail }: { icon: typeof BarChart3; label: string; value: string; detail: string }) { return <div className="border border-white/10 bg-charcoal-50/60 p-5"><Icon className="h-5 w-5 text-gold" /><p className="mt-5 text-xs uppercase tracking-wider text-ivory/45">{label}</p><p className="mt-1 font-display text-3xl text-ivory">{value}</p><p className="mt-1 text-xs text-ivory/45">{detail}</p></div>; }
function Chart({ title, data, suffix }: { title: string; data: [string, number][]; suffix: string }) { const max = Math.max(...data.map(([, value]) => value), 1); return <div className="border border-white/10 bg-charcoal-50/60 p-5"><h2 className="font-display text-xl text-ivory">{title}</h2><div className="mt-6 space-y-4">{data.length ? data.map(([label, value]) => <div key={label}><div className="mb-1 flex justify-between text-xs"><span className="truncate text-ivory/65">{label}</span><span className="text-gold">{value}{suffix}</span></div><div className="h-2 bg-white/10"><div className="h-full bg-gold transition-all" style={{ width: `${(value / max) * 100}%` }} /></div></div>) : <p className="text-sm text-ivory/45">Aún no hay datos suficientes.</p>}</div></div>; }
function Finance({ label, value, total, color }: { label: string; value: number; total: number; color: string }) { const percentage = total ? Math.min((value / total) * 100, 100) : 0; return <div><div className="mb-2 flex justify-between text-sm"><span className="text-ivory/65">{label}</span><span className="text-gold">{formatPrice(value)}</span></div><div className="h-3 bg-white/10"><div className={`h-full ${color}`} style={{ width: `${percentage}%` }} /></div></div>; }
